sudo: required
services:
  - docker

before_install:
  - docker build -t bretstateham/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bretstateham/react-test npm run test -- --coverage

after_success:
  - docker build -t bretstateham/multi-client ./client 
  - docker build -t bretstateham/multi-nginx ./nginx
  - docker build -t bretstateham/multi-server ./server
  - docker build -t bretstateham/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push bretstateham/multi-client
  - docker push bretstateham/multi-nginx
  - docker push bretstateham/multi-server
  - docker push bretstateham/multi-worker